### ISSUE TITLE
حذف از سرور

### ISSUE THREAD

**Issue by Morghak963** [benyamin218118/tcpforwarder#1]
سلام 
چطور میشه این دستور رو از سرور حذف نمود؟

**Comment by benyamin218118** [comment]
سلام @Morghak963 
اگر با screen اجرا کردین  باید بااستفاده از screen -list اسم session مربوطه رو پیدا کنین و با screen -x sessionName وارد screen session مربوطه بشین و با ctrl+c دستور رو متوقف کنین و با وارد کردن exit نشست فعال screen رو ببندین

اگر با systemd unit file اجرا کردین مطمئنا یه فایل توی مسیری مشابه /etc/systemd/system/ ساختین و اسم فایل مثلا myforwarder.service هست که با استفاده از service myforwarder stop میتونین اجرا رو متوقف کنین

اگر هیچ کدوم این دو مورد نیست و به این صورت اجرا کردین : 
./tcpforwarder -lPort 8080 -rHost 1.2.3.4 -rPort 8090

بعد از بستن ssh اجرا متوقف میشه
اگر هم خواستین میتونین با این دستور کل tcpforwarder هایی که در حال اجرا هست رو ببندین : 
killall tcpforwarder

اگر منظور از حذف دستور حذف فایل و نصب هست ازونجایی که فقط ابزار رو دانلود کردین و نصبی در کار نبوده میتونین از مسیری که دانلودش کردین مثل فایل های دیگه حذفش کنین.

**Comment by Morghak963** [comment]
ممنون بابت توضیحاتتون
مهندس جان 
ای کاش نحوه ایجاد system unit file هم با جزئیات توضیح می‌دادید که افراد مبتدی گیج نشن
ممنون میشم

**Comment by benyamin218118** [comment]
@Morghak963 
وقت کنم حتما اضافه میکنم
ببینم بهترین راه چیه حتما به document اضافه میکنم

فکر میکنم در مورد حذف از سرور توضیحات کافی بوده, issue رو close میکنم پس.
اگر توضیحات بیشتری لازم بود میتونین مجدد باز کنین.

**Comment by benyamin218118** [comment]
@Morghak963 
درخواست اضافه شد
قسمت مربوطه :

How to Keep The Process Alive

**Comment by Morghak963** [comment]
بسیارعالی متشکرم،موفق باشید
